#!/bin/bash -ex
#

# Prepare the environment:
if [ -z "$1" ]
  then
    echo "No cluster id supplied"
    exit 1
fi

ocm get $(ocm get $(ocm get cluster "$1" | jq -r .subscription.href) | jq -r .creator.href)
