#!/bin/bash -ex
#

# Prepare the environment:
if [ -z "$1" ]
  then
    echo "No cluster id supplied"
fi

clusterName="$(ocm get cluster $1 | jq -r .name)"

ocm get cluster "$1/credentials" | jq -r ".kubeconfig" > ~/kubeconfigs/"$clusterName"

echo "you can now use kubeconfig for $clusterName"
