#!/bin/bash -e
#

# Prepare the environment:
if [ -z "$1" ]
  then
    echo "No cluster id supplied"
    exit 1
fi
if [ -z "$2" ]
  then
    echo "No nodepool id supplied"
    exit 1
fi

ocm get cluster "$1/resources/live" | jq -r ".resources[\"manifest_work-$1-$2\"]" | jq
