#!/bin/bash -e
#
# Wrapper for ocm login. Mostly useful to also logout
# and handle local dev
# By default using Service account credentials in the env
# OCM_SA_CLIENT_ID OCM_SA_CLIENT_SECRET, unless passing a flag
#
# Usage: ocmLogin [-a] valid-environment

# Prepare the environment:
auth_code=false
while getopts a flag
do
    case "${flag}" in
        a) auth_code=true; echo "Using auth_code instead of service account"; shift;;
    esac
done

if [ -z "$1" ]
  then
    echo "No environment supplied"
    exit 1
fi

case $1 in
    local)
        url="--url=http://localhost:9000 --insecure"
        ;;

    int | integration)
        url="--url=integration"
        ;;

    stg | stage | staging)
        url="--url=stage"
        ;;

    prd | prod | production)
        url="--url=production"
        ;;

    *)
        echo "Invalid environment!"
        exit 1
        ;;
esac


ocm logout
if $auth_code;
then
    ocm login --use-auth-code $(echo "${url}")
else
    ocm login --client-id "${OCM_SA_CLIENT_ID}" --client-secret "${OCM_SA_CLIENT_SECRET}" $(echo "${url}")
fi


echo ""
echo "Now logged in $1!"
echo ""
# ocm whoami doesn't show the endpoint
rosa whoami
